name: GitHub Pages Pre-deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checks out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
    
      - name: Install node packages
        run: npm install

      - name: Build the static site
        run: make build/release
        
      - name: Deploy to GitHub pages
        if: ${{ success() }}
        uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
        with:
          target_branch: gh-pages
          build_dir: build/release/final
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
